// Generated by Melange

import * as React from "react";
import * as Feature1$Feature1 from "@melange-nx/feature1/./src/lib/feature1.bs.js";
import * as RescriptReactRouter from "@rescript/react/./src/RescriptReactRouter.bs.js";

import './app.css';
;

function App$HomePage(Props) {
  return React.createElement("div", {
              className: "app"
            }, React.createElement("header", {
                  className: "flex"
                }, React.createElement("h1", undefined, "Welcome to web!")), React.createElement("main", undefined, React.createElement("h2", undefined, "Resources & Tools")));
}

var HomePage = {
  make: App$HomePage
};

function App(Props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  if (!match) {
    return React.createElement(App$HomePage, {});
  }
  if (match.hd === "feature") {
    var match$1 = match.tl;
    if (match$1 && match$1.hd === "1" && !match$1.tl) {
      return React.createElement(Feature1$Feature1.make, {});
    }
    
  }
  throw {
        RE_EXN_ID: "Match_failure",
        _1: [
          "App.re",
          19,
          2
        ],
        Error: new Error()
      };
}

var make = App;

export {
  HomePage ,
  make ,
  
}
/*  Not a pure module */
