// Generated by Melange

import * as App from "./app/App.bs.js";
import * as React from "react";
import * as ReactDom from "react-dom";

ReactDom.render(React.createElement(App.make, {}), document.getElementById("root"));

export {
  
}
/*  Not a pure module */
