// Generated by Melange

import * as React from "react";

import './feature1.module.css';
;

function Feature1(Props) {
  return React.createElement("div", undefined, React.createElement("h1", undefined, "Welcome to Feature1"));
}

var make = Feature1;

export {
  make ,
  
}
/*  Not a pure module */
